### ISSUE TITLE
腳本無法執行

### ISSUE THREAD

**Issue by linwajun** [ayaka14732/OpenCCFontGenerator#2]
Archive:  fonts/GenYoMin.zip
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/OpenCCFontGenerator-0.0.1-py3.8.egg/OpenCCFontGenerator/__main__.py", line 35, in <module>
    main()
  File "/usr/local/lib/python3.8/dist-packages/OpenCCFontGenerator-0.0.1-py3.8.egg/OpenCCFontGenerator/__main__.py", line 20, in main
    '--twp', action=argparse.BooleanOptionalAction, default=False, help='whether to convert with Taiwanese phrases')
AttributeError: module 'argparse' has no attribute 'BooleanOptionalAction'

我是個小白
基本上是按照網路上的教程一步步慢慢來 
先灌pip 安裝setup.py 然後跑build.sh
但最後卡在這個地方

**Comment by ayaka14732** [comment]
在 <https://docs.python.org/3/library/argparse.html> 上查到 `BooleanOptionalAction` 是 New in version 3.9，所以 Python 3.8 用不到。

目前腳本還不是很完善，如果需要幫忙 build 可以直接提 issue～

**Comment by ayaka14732** [comment]
現在可以用 AI agent 協助除錯
